#!/bin/sh
set -e -u
cp -r tests "$AUTOPKGTEST_TMP/"
cd "$AUTOPKGTEST_TMP"
pyversions -i \
| tr ' ' '\n' \
| xargs -I {} env PYTHONWARNINGS=d PYTHONHASHSEED=random {} \
  -m pytest -vv --ignore tests/test_websupport.py --ignore tests/test_api_translator.py 2>&1

# vim:ts=4 sw=4 et
